---
- name: install and configure mariadb
  hosts: group1
  remote_user: ec2-user
  become: yes

  vars: 
    mysql_port: 3306

  tasks: 
  - name: install mariadb
    yum: name={{item}} state=installed
    with_items:
    - mariadb-server
    - MySQL-python
    - libselinux-python

  - name: create mysql config file
    template: src=my.cnf.j2 dest=/etc/my.cnf
    notify: restart mariadb

  - name: configure logfile 
    file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

  - name: start mariadb service
    service: name=mariadb state=started enabled=yes

  handlers:
  - name: restart mariadb
    service: name=mariadb state=restarted
